# Generated by Django 5.1.15 on 2026-10-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('advocate_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('practice_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('feature', models.CharField(db_index=True, max_length=32)),
                ('operation', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated', models.BooleanField(default=False)),
                ('characters', models.IntegerField(blank=True, null=True)),
                ('ref_type', models.CharField(blank=True, default='', max_length=32)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'llm_usage',
                'indexes': [models.Index(fields=['feature', 'created_at'], name='llm_usage_feature_b9e38d_idx')],
            },
        ),
    ]
