# Generated by Django 5.1.15 on 2026-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_root_id', models.BigIntegerField(unique=True)),
                ('firm_root_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firm_team',
            },
        ),
    ]
