# Generated by Django 5.1.15 on 2026-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTerm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=255)),
                ('term_norm', models.CharField(db_index=True, max_length=255)),
                ('definition', models.TextField()),
                ('letter', models.CharField(blank=True, default='', max_length=8)),
                ('source', models.CharField(default='blacks-1910', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'legal_term',
                'ordering': ['term'],
                'managed': True,
            },
        ),
    ]
