# Generated by Django 5.1.15 on 2026-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalterm',
            name='definition_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
