# Generated by Django 5.1.15 on 2026-09-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_legalterm_definition_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalterm',
            name='hindi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
