# Generated by Django 5.1.15 on 2026-07-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('forum', models.CharField(default='Supreme Court', max_length=255)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('case_year', models.CharField(blank=True, max_length=8, null=True)),
                ('judgement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appeal_alert',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
