# Generated by Django 5.1.15 on 2026-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealDetection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('source_case_id', models.BigIntegerField(db_index=True)),
                ('source_case_number', models.CharField(blank=True, default='', max_length=255)),
                ('forum_court_id', models.CharField(max_length=32)),
                ('forum_state_code', models.CharField(blank=True, default='', max_length=8)),
                ('forum_label', models.CharField(blank=True, default='', max_length=255)),
                ('appeal_case_number', models.CharField(blank=True, default='', max_length=255)),
                ('appeal_cnr', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('appeal_parties', models.CharField(blank=True, default='', max_length=500)),
                ('appeal_filed_on', models.DateField(blank=True, null=True)),
                ('matched_on', models.CharField(blank=True, default='', max_length=255)),
                ('match_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed as an appeal'), ('DISMISSED', 'Not related')], default='NEW', max_length=16)),
                ('notified_in_app', models.BooleanField(default=False)),
                ('notified_email', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appeal_detection',
                'ordering': ['-detected_at', '-id'],
                'indexes': [models.Index(fields=['advocate_id', 'status'], name='appeal_dete_advocat_60db99_idx')],
                'constraints': [models.UniqueConstraint(fields=('advocate_id', 'source_case_id', 'appeal_cnr'), name='uniq_appeal_per_source_case')],
            },
        ),
    ]
