# Generated by Django 5.1.15 on 2026-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_appealdetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppealAlert',
        ),
    ]
