# Generated by Django 5.1.15 on 2026-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.BigIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('key_points_json', models.TextField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=128, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_summary',
                'managed': True,
            },
        ),
    ]
