# Generated by Django 5.1.15 on 2026-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.BigIntegerField(db_index=True)),
                ('version', models.IntegerField()),
                ('stored_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_version',
                'ordering': ['-version'],
                'managed': True,
                'unique_together': {('document_id', 'version')},
            },
        ),
    ]
