# Generated by Django 5.1.15 on 2026-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
