# Generated by Django 5.1.15 on 2026-08-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('long_title', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('preamble_html', models.TextField(blank=True)),
                ('source_state_name', models.CharField(max_length=128)),
                ('act_number', models.CharField(blank=True, max_length=32)),
                ('act_year', models.IntegerField(blank=True, null=True)),
                ('ministry_name', models.CharField(blank=True, max_length=256)),
                ('department_name', models.CharField(blank=True, max_length=256)),
                ('enact_date', models.DateField(blank=True, null=True)),
                ('enforcement_date', models.TextField(blank=True)),
                ('repealed', models.BooleanField(default=False)),
                ('no_of_chapter', models.IntegerField(default=0)),
                ('no_of_section', models.IntegerField(default=0)),
                ('pdf_url', models.URLField(blank=True, max_length=1024)),
                ('source_uuid', models.CharField(max_length=64)),
                ('source_act_id', models.CharField(blank=True, max_length=128)),
                ('source_state_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'acts_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'acts_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('footnote', models.TextField(blank=True)),
                ('order_number', models.IntegerField(default=0)),
                ('source_section_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'acts_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActCaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.BigIntegerField()),
                ('advocate_id', models.BigIntegerField()),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='acts.act')),
            ],
            options={
                'unique_together': {('act', 'case_id')},
            },
        ),
    ]
