# Generated by Django 5.1.15 on 2026-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.FloatField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['invoice_id'], name='invoice_ite_invoice_ab1faa_idx')],
            },
        ),
    ]
