# Generated by Django 5.1.15 on 2026-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_id', models.BigIntegerField(unique=True)),
                ('pay_in_favour_of', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_branch_address', models.CharField(blank=True, default='', max_length=500)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=32)),
                ('micr_code', models.CharField(blank=True, default='', max_length=32)),
                ('remittance_email', models.CharField(blank=True, default='', max_length=255)),
                ('hsn_code', models.CharField(blank=True, default='998212', max_length=32)),
                ('service_category', models.CharField(blank=True, default='LEGAL SERVICES', max_length=128)),
                ('gst_note', models.TextField(blank=True, default='GST on Legal Services is payable by the recipient of service on reverse charge basis. (CGST 9% + SGST/UTGST 9% OR IGST 18% AS THE CASE MAY BE). Please also note the time of supply for this invoice will be 60 days from the date of Invoice unless Payment is made earlier. Non payment of GST beyond 60 days will attract interest as per GST Law.')),
                ('iso_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'firm_billing_profile',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField(unique=True)),
                ('kind_attn', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_gstin', models.CharField(blank=True, default='', max_length=32)),
                ('recipient_state', models.CharField(blank=True, default='', max_length=128)),
                ('recipient_state_code', models.CharField(blank=True, default='', max_length=8)),
                ('recipient_address', models.TextField(blank=True, default='')),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_tax_detail',
                'indexes': [models.Index(fields=['invoice_id'], name='invoice_tax_invoice_32d969_idx')],
            },
        ),
    ]
