# Generated by Django 5.1.15 on 2026-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_firmbillingprofile_invoicetaxdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='cgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='gst_rate',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='igst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='sgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='tax_mode',
            field=models.CharField(default='rcm', max_length=16),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='taxable_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoicetaxdetail',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
