# Generated by Django 5.1.15 on 2026-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField(unique=True)),
                ('issued_by_id', models.BigIntegerField(null=True)),
                ('cancelled_by_id', models.BigIntegerField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoice_handling',
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.BigIntegerField(unique=True)),
                ('invoice_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_invoice',
            },
        ),
    ]
