# Generated by Django 5.1.15 on 2026-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_payment_link_and_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehandling',
            name='client_notified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
