# Generated by Django 5.1.15 on 2026-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('case_id', models.BigIntegerField(db_index=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_note',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('case_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(default='MEDIUM', max_length=16)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_task',
                'ordering': ['completed', 'deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('case_id', models.BigIntegerField(db_index=True)),
                ('label', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_tag',
                'ordering': ['label'],
                'unique_together': {('advocate_id', 'case_id', 'label')},
            },
        ),
    ]
