# Generated by Django 5.1.15 on 2026-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('case_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('counsel', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_opponent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_party',
                'ordering': ['-is_opponent', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RelatedCase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('case_id', models.BigIntegerField(db_index=True)),
                ('related_case_id', models.BigIntegerField(db_index=True)),
                ('relation', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_related',
                'ordering': ['-id'],
                'unique_together': {('advocate_id', 'case_id', 'related_case_id')},
            },
        ),
    ]
