# Generated by Django 5.1.15 on 2026-08-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_caseparty_relatedcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetask',
            name='case_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='CaseTaskDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('task_id', models.BigIntegerField(db_index=True)),
                ('document_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_task_document',
                'ordering': ['id'],
                'unique_together': {('task_id', 'document_id')},
            },
        ),
    ]
