# Generated by Django 5.1.15 on 2026-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_casetask_case_id_casetaskdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.BigIntegerField(db_index=True, unique=True)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=64)),
                ('court', models.CharField(blank=True, default='', max_length=255)),
                ('bench_hall', models.CharField(blank=True, default='', max_length=128)),
                ('judge', models.CharField(blank=True, default='', max_length=255)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hearing_detail',
            },
        ),
    ]
