# Generated by Django 5.1.15 on 2026-09-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_hearingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='assigned_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='assigned_to_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
