# Generated by Django 5.1.15 on 2026-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_backfill_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
