# Generated by Django 5.1.15 on 2026-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_casetask_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='review_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='reviewed_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casetask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
