# Generated by Django 5.1.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_task_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.BigIntegerField(db_index=True)),
                ('submitted_by_id', models.BigIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_task_submission',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
