# Generated by Django 5.1.15 on 2026-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_task_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='draft_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
