# Generated by Django 5.1.15 on 2026-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_task_submission_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_id', models.BigIntegerField(unique=True)),
                ('matter_type', models.CharField(choices=[('litigation', 'Litigation'), ('pre_filing', 'Not filed yet'), ('non_litigation', 'Non-litigation (notice, advisory, contract)')], default='litigation', max_length=20)),
                ('court_name', models.CharField(blank=True, default='', max_length=255)),
                ('court_hall', models.CharField(blank=True, default='', max_length=64)),
                ('judge', models.CharField(blank=True, default='', max_length=255)),
                ('our_side', models.CharField(blank=True, default='', max_length=32)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('case_year', models.IntegerField(blank=True, null=True)),
                ('cnr', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('acts_sections', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_profile',
            },
        ),
    ]
