# Generated by Django 5.1.15 on 2026-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCodeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_act', models.CharField(choices=[('IPC', 'Indian Penal Code, 1860'), ('CrPC', 'Code of Criminal Procedure, 1973'), ('IEA', 'Indian Evidence Act, 1872')], db_index=True, max_length=10)),
                ('old_section', models.CharField(max_length=30)),
                ('old_section_norm', models.CharField(db_index=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('new_act', models.CharField(choices=[('BNS', 'Bharatiya Nyaya Sanhita, 2023'), ('BNSS', 'Bharatiya Nagarik Suraksha Sanhita, 2023'), ('BSA', 'Bharatiya Sakshya Adhiniyam, 2023')], max_length=10)),
                ('new_section', models.CharField(blank=True, default='', max_length=30)),
                ('new_section_norm', models.CharField(db_index=True, default='', max_length=30)),
                ('changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'legal_code_mapping',
                'ordering': ['old_act', 'old_section'],
                'managed': True,
                'unique_together': {('old_act', 'old_section')},
            },
        ),
    ]
