# Generated by Django 5.1.15 on 2026-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcodemapping',
            name='source',
            field=models.CharField(default='vakilpedia', max_length=40),
        ),
        migrations.AlterField(
            model_name='legalcodemapping',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='legalcodemapping',
            name='new_section',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='legalcodemapping',
            name='new_section_norm',
            field=models.CharField(db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='legalcodemapping',
            name='old_section',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='legalcodemapping',
            name='old_section_norm',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
    ]
