# Generated by Django 5.1.15 on 2026-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(unique=True)),
                ('advocate_id', models.BigIntegerField(db_index=True)),
                ('assigned_by_id', models.BigIntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_handler',
            },
        ),
    ]
