# Generated by Django 5.1.15 on 2026-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('billing_currency', models.CharField(blank=True, default='INR', max_length=8)),
                ('gstin', models.CharField(blank=True, default='', max_length=32)),
                ('building', models.CharField(blank=True, default='', max_length=255)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('pincode', models.CharField(blank=True, default='', max_length=16)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_profile',
            },
        ),
    ]
