# Generated by Django 5.1.15 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_id', models.BigIntegerField()),
                ('case_id', models.BigIntegerField(blank=True, null=True)),
                ('court_id', models.CharField(max_length=64)),
                ('query', models.JSONField(default=dict)),
                ('raw', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courtsearch_imported_record',
                'indexes': [models.Index(fields=['advocate_id', 'case_id'], name='courtsearch_advocat_8647a9_idx')],
            },
        ),
    ]
