# Generated by Django 5.1.15 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtsearch', '0002_importedcaserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=32)),
                ('list_date', models.DateField()),
                ('court_number', models.CharField(max_length=16)),
                ('item_number', models.CharField(max_length=32)),
                ('case_string', models.CharField(max_length=255)),
                ('case_type', models.CharField(blank=True, max_length=32)),
                ('case_no', models.CharField(blank=True, max_length=32)),
                ('case_year', models.CharField(blank=True, max_length=8)),
                ('diary_number', models.CharField(blank=True, max_length=64)),
                ('list_type', models.CharField(default='DAILY', max_length=16)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'causelist_item',
                'indexes': [models.Index(fields=['court', 'list_date'], name='causelist_i_court_1c53b9_idx'), models.Index(fields=['court', 'list_date', 'case_type', 'case_no', 'case_year'], name='causelist_join_idx')],
            },
        ),
    ]
