# Generated by Django 5.1.15 on 2026-09-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtsearch', '0003_causelistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causelistitem',
            name='court_number',
            field=models.CharField(max_length=100),
        ),
    ]
