# Generated by Django 5.1.15 on 2026-09-24 12:18

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Drafting tables live in their own schema and use pgvector (both already exist in
        # InstaDraft's database; this makes a fresh database work too).
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS drf', reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ams_client_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"drf"."client"',
            },
        ),
        migrations.CreateModel(
            name='DraftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('block_type', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('content_html', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('style_json', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('sample_clause', 'Sample Clause'), ('prompt', 'User Prompt'), ('generated', 'AI Generated')], max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('legal_code_replacements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"drf"."draft_block"',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('scratch', 'Write from Scratch'), ('document', 'Generate from Documents')], max_length=20)),
                ('llm_provider', models.CharField(choices=[('gemini', 'Gemini')], default='gemini', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_by_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"drf"."playbook"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('slot_schema', models.JSONField(default=list)),
                ('body_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"drf"."template"',
            },
        ),
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('facts', models.JSONField(default=dict)),
                ('llm', models.CharField(default='gemini', max_length=20)),
                ('mode', models.CharField(choices=[('template', 'Template + documents'), ('sample', 'Documents only'), ('library', 'From scratch (clause library)')], default='template', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('risk_status', models.CharField(default='idle', max_length=20)),
                ('risk_report', models.JSONField(blank=True, null=True)),
                ('apply_bns_codes', models.BooleanField(default=False)),
                ('ams_task_id', models.BigIntegerField(blank=True, null=True)),
                ('ams_document_id', models.BigIntegerField(blank=True, null=True)),
                ('ams_document_version', models.IntegerField(blank=True, null=True)),
                ('ams_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='drafting.client')),
            ],
            options={
                'db_table': '"drf"."draft_session"',
            },
        ),
        migrations.CreateModel(
            name='DraftEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('before_text', models.TextField(blank=True)),
                ('after_text', models.TextField(blank=True)),
                ('before_html', models.TextField(blank=True)),
                ('after_html', models.TextField(blank=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_by_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='drafting.draftblock')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."draft_edit"',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='draftblock',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='drafting.draftsession'),
        ),
        migrations.CreateModel(
            name='LegalCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_act', models.CharField(choices=[('IPC', 'Indian Penal Code, 1860'), ('CrPC', 'Code of Criminal Procedure, 1973'), ('IEA', 'Indian Evidence Act, 1872')], db_index=True, max_length=10)),
                ('old_section', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('new_act', models.CharField(choices=[('BNS', 'Bharatiya Nyaya Sanhita, 2023'), ('BNSS', 'Bharatiya Nagarik Suraksha Sanhita, 2023'), ('BSA', 'Bharatiya Sakshya Adhiniyam, 2023')], max_length=10)),
                ('new_section', models.CharField(blank=True, max_length=30)),
                ('changed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"drf"."legal_code_mapping"',
                'ordering': ['old_act', 'old_section'],
                'unique_together': {('old_act', 'old_section')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='drafting.client')),
            ],
            options={
                'db_table': '"drf"."member"',
            },
        ),
        migrations.AddField(
            model_name='draftsession',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='drafting.member'),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='drafting.playbook'),
        ),
        migrations.CreateModel(
            name='PlaybookClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('standard_text', models.TextField()),
                ('red_lines', models.JSONField(default=list)),
                ('fallback_positions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('source_doc_count', models.PositiveIntegerField(default=1)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='drafting.playbook')),
            ],
            options={
                'db_table': '"drf"."playbook_clause"',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='playbooks/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drafting.playbook')),
            ],
            options={
                'db_table': '"drf"."playbook_document"',
            },
        ),
        migrations.CreateModel(
            name='PlaybookClauseRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=100)),
                ('raw_text', models.TextField()),
                ('extracted_json', models.JSONField(default=dict)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_clauses', to='drafting.playbook')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafting.playbookdocument')),
            ],
            options={
                'db_table': '"drf"."playbook_clause_raw"',
            },
        ),
        migrations.CreateModel(
            name='PlaybookRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], max_length=20)),
                ('issue', models.TextField()),
                ('suggestion', models.TextField()),
                ('quote', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='drafting.draftblock')),
                ('playbook_clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafting.playbookclause')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."playbook_risk"',
                'ordering': ['severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ams_case_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='drafting.client')),
            ],
            options={
                'db_table': '"drf"."project"',
            },
        ),
        migrations.AddField(
            model_name='draftsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='drafting.project'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('variant', models.CharField(blank=True, default='any', max_length=20)),
                ('file', models.FileField(upload_to='samples/')),
                ('uploaded_by_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('summary_status', models.CharField(choices=[('idle', 'Idle'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('translation', models.TextField(blank=True, default='')),
                ('translation_json', models.JSONField(blank=True, default=list)),
                ('translation_target', models.CharField(blank=True, max_length=10)),
                ('translation_source', models.CharField(blank=True, max_length=10)),
                ('translation_status', models.CharField(choices=[('idle', 'Idle'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('ams_document_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ams_version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='drafting.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='drafting.project')),
            ],
            options={
                'db_table': '"drf"."sample"',
            },
        ),
        migrations.AddField(
            model_name='playbookdocument',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_documents', to='drafting.sample'),
        ),
        migrations.CreateModel(
            name='LibraryClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=100)),
                ('clause_type', models.CharField(blank=True, max_length=100)),
                ('variant', models.CharField(choices=[('any', 'Any'), ('mutual', 'Mutual'), ('one_way', 'One-way')], default='any', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('conditions', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_clauses', to='drafting.sample')),
            ],
            options={
                'db_table': '"drf"."library_clause"',
                'ordering': ['contract_type', 'title'],
            },
        ),
        migrations.AddField(
            model_name='draftsession',
            name='samples',
            field=models.ManyToManyField(related_name='sessions', to='drafting.sample'),
        ),
        migrations.CreateModel(
            name='SampleClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='drafting.sample')),
            ],
            options={
                'db_table': '"drf"."sample_clause"',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='draftblock',
            name='source_clause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_blocks', to='drafting.sampleclause'),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='drafting.template'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('uploaded_by_id', 'ams_document_id'), name='sample_one_import_per_user'),
        ),
    ]
