# Generated by Django 5.1.15 on 2026-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0002_project_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftsession',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
