# Generated by Django 5.1.15 on 2026-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0003_retire_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('generated', 'AI draft'), ('sent', 'Sent to AMS / review'), ('manual', 'Saved by user')], default='manual', max_length=20)),
                ('blocks', models.JSONField(default=list)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."draft_version"',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'number'), name='draft_version_unique_number')],
            },
        ),
    ]
