# Generated by Django 5.1.15 on 2026-10-08 17:07

from django.db import migrations, models


def assign_template_owners(apps, schema_editor):
    """Templates had no creator. Give each one an owner so it is scoped to a firm:
    whoever first drafted with it; otherwise, when all existing drafting set-up
    (playbooks and templates already owned) belongs to one person, that person.
    Anything still unknown stays unowned (only a Super Admin can manage it)."""
    Template = apps.get_model('drafting', 'Template')
    DraftSession = apps.get_model('drafting', 'DraftSession')
    Playbook = apps.get_model('drafting', 'Playbook')
    for t in Template.objects.filter(created_by_id__isnull=True):
        first = (DraftSession.objects.filter(template_id=t.id, created_by_id__isnull=False)
                 .order_by('id').values_list('created_by_id', flat=True).first())
        if first:
            t.created_by_id = first
            t.save(update_fields=['created_by_id'])
    owners = set(Playbook.objects.exclude(created_by_id__isnull=True).values_list('created_by_id', flat=True))
    owners |= set(Template.objects.exclude(created_by_id__isnull=True).values_list('created_by_id', flat=True))
    if len(owners) == 1:
        Template.objects.filter(created_by_id__isnull=True).update(created_by_id=owners.pop())


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0003_retire_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbook',
            name='archived_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='archived_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_by_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(assign_template_owners, migrations.RunPython.noop),
    ]
