# Generated by Django 5.1.15 on 2026-10-08 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0004_draft_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftversion',
            name='kind',
            field=models.CharField(choices=[('generated', 'AI draft'), ('sent', 'Sent to AMS / review'), ('manual', 'Saved by user'), ('review', 'After a review round')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='DraftReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_id', models.BigIntegerField()),
                ('reviewer_id', models.BigIntegerField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('authority', models.CharField(choices=[('binding', 'May correct and suggest'), ('suggest', 'Suggestions only')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."draft_review_request"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('suggestions', 'Suggestions'), ('changes', 'Changes to review')], max_length=20)),
                ('binding', models.BooleanField(default=False)),
                ('author_id', models.BigIntegerField()),
                ('decider_id', models.BigIntegerField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('base_blocks', models.JSONField(default=list)),
                ('target_blocks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('review_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='drafting.draftreviewrequest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."draft_review_round"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftChangeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('accepted', 'Accepted / kept'), ('declined', 'Declined (suggestion)'), ('rejected', 'Rejected (change undone)'), ('queried', 'Queried (binding correction)'), ('acknowledged', 'Acknowledged (binding correction)')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('decided_by_id', models.BigIntegerField()),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='drafting.draftreviewround')),
            ],
            options={
                'db_table': '"drf"."draft_change_decision"',
                'constraints': [models.UniqueConstraint(fields=('round', 'change_id'), name='draft_change_decision_once')],
            },
        ),
    ]
