# Generated by Django 5.1.15 on 2026-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0005_review_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftversion',
            name='kind',
            field=models.CharField(choices=[('generated', 'AI draft'), ('sent', 'Sent to AMS / review'), ('manual', 'Saved by user'), ('review', 'After a review round'), ('returned', 'Sent back for changes')], default='manual', max_length=20),
        ),
    ]
