# Generated by Django 5.1.15 on 2026-10-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0007_review_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.BigIntegerField(blank=True, null=True)),
                ('quote', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('author_id', models.BigIntegerField(db_index=True)),
                ('resolved_by_id', models.BigIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='drafting.draftcomment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drafting.draftsession')),
            ],
            options={
                'db_table': '"drf"."draft_comment"',
                'ordering': ['created_at'],
            },
        ),
    ]
