# Generated by Django 5.1.15 on 2026-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0009_comment_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftreviewround',
            name='external_from',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
