# Generated by Django 5.1.15 on 2026-10-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0004_playbook_template_owner_archive'),
        ('drafting', '0010_round_external_from'),
    ]

    operations = [
    ]
